version: '3.5'

services:

  postgres:
    container_name: radiusfriend_postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"